jobs:
  - job: Build
    variables:
      - template: ../variables/globals.yml
    pool:
      vmImage: windows-2019
    steps:
    - ${{ each artifact in parameters.Artifacts }}:
      - template: /eng/common/pipelines/templates/steps/verify-changelog.yml
        parameters:
          ServiceName: ${{ parameters.ServiceDirectory}}
          PackageName: ${{ artifact.name}}